### ISSUE TITLE
option to include original object in `read`

### ISSUE THREAD

**Issue by mmckegg** [flumedb/flumeview-query#6]
Maybe add a {values: true} option to `links` that allows you to retrieve the original message so that you don't need to do a seperate lookup in the client.

Or this could become the default behaviour and match `flumeview-query/index`.

This would help close https://github.com/ssbc/ssb-backlinks/issues/4

**Comment by arj03** [comment]
This seems to have been fixed here: https://github.com/flumedb/flumeview-query/commit/ac55bd2feed0dc8f706781e80a93dea40cfc5ffc

**Comment by arj03** [comment]
No actually that is something else. Got the values option confused.
